version: "3"
 
services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
 
  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitexchange
      - gems:/gems
 
 
volumes:
  postgres:
  gems: